import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import Link from 'next/link';

const Nav = dynamic(() => import('subscriberApp/nav'));
const Footer = dynamic(() => import('subscriberApp/footer'));

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav>This is nav in travel advisor, it is component of subscriber app</Nav>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>
          Welcome to travel advisor app port: 3001
        </h1>
        <Link href="/destinations">destinations</Link>
      </main>
      <Footer></Footer>
    </>
  );
}
